// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"CustomLogo","status":true,"description":"Shows RPG Maker and user logos at the start of the game.","parameters":{"logo1":"","logo1ImageName":"MadeWithMv","logo1Skippable":"true","logo1Coordinate":"","logo1X":"408","logo1Y":"312","logo1Origin":"0.5","logo1Time":"","logo1FadeinFrames":"12","logo1FadeoutFrames":"12","logo1DurationFrames":"120","logo2":"","logo2ImageName":"","logo2Skippable":"true","logo2Coordinate":"","logo2X":"408","logo2Y":"312","logo2Origin":"0.5","logo2Time":"","logo2FadeinFrames":"12","logo2FadeoutFrames":"12","logo2DurationFrames":"120","logo3":"","logo3ImageName":"","logo3Skippable":"true","logo3Coordinate":"","logo3X":"408","logo3Y":"312","logo3Origin":"0.5","logo3Time":"","logo3FadeinFrames":"12","logo3FadeoutFrames":"12","logo3DurationFrames":"120","allowTotalSkip":"true"}},
{"name":"QuickPlayMap","status":false,"description":"Quick Playtest from a specific map (RPG Maker MV)","parameters":{}},
{"name":"GALV_PuzzleFunctions","status":true,"description":"(v.1.1) A bunch of functions to use to make eventing puzzles easier","parameters":{}},
{"name":"ExitButtonOnTitle","status":true,"description":"Adds an \"Exit Game\" option to the title screen.","parameters":{}},
{"name":"GALV_CursorImage","status":true,"description":"(v.1.8) Display an animated image next to the selected menu command.","parameters":{"Cursor Image":"WindowCursor","Image Frames":"4","Position Centered":"true","Position Offset":"0,0","Animation Speed":"6","Command Indent":"0","Item Indent":"0","Start Hidden":"false"}}
];
